### ISSUE TITLE
listgroupsandmembers.py not outputting all groups and members

### ISSUE THREAD

**Issue by FDever17** [sassoftware/pyviyatools#54]
Hi, 
I am running the listgroupsandmembers.py tool which, as I understand it, should give me a list of all of the custom groups within Viya 3.5 and all of it's members (both users and other groups). We have a large number of custom groups, however it doesn't seem to be pulling it all through all of the groups. I am combining this output with that of the listeffectivepermissions.sh shell script to produce a full list of permissions on folders so we can see what each user/group has access to.

The resultant output has missing values. The listeffectivepermissions.sh will output a file that contains the "Developer" group, but this group does not appear in the output of the listgroupsandmembers.py. If you could have a look or if I am missing something with regards to the usage, let me know.

Thanks, 
Fraser

**Comment by dwstern** [comment]
Hi Fraser,

Thanks for getting in touch - I wrote that script, so hopefully I can help. But I may need to ask you to try a possible fix first, if you feel confident trying that?

I suspect that if you have a large number of groups, you may be hitting a limit of groups or members returned from one of the REST API calls. I don't know what that limit is, but if you were to look at the JSON result's count property, I'd bet it's some multiple of 10 (i.e. 1000, 10000 or something like that). We could try adding (or changing) a limit= parameter in the REST endpoint URI, we should be able to increase the number or rows it returns.

The environment I develop these tools on doesn't have a particularly large set of groups (several tens of groups) or members in it (also several tens of users), which probably explains why I've not run into the issue you're encountering, but I have had very similar-sounding issues with other tools where there are much larger result sets.

May I ask you to try something to see if it fixes the problem for you? If it does, I'll make the change (or you can!) to the code so it works for everyone. Would you try this:

- On line 66 of listgroupsandmembers.py, try changing endpoint='/identities/groups' to endpoint='/identities/groups?limit=10000'

- On line 85 of the same file: change endpoint='/identities/groups/'+groupid+'/members' to endpoint='/identities/groups/'+groupid+'/members?limit=10000'

- On line 108 of the same file: change endpoint='/identities/users/'+memberid to endpoint='/identities/users/'+memberid + '/limit=10000'

Feel free to experiment with larger or smaller limit values than 10000. If performance is terrible, we can keep a lower limit and I can change the code to page through the results, say 1000 rows at a time. But in my experience with other endpoints, getting many thousands of 'rows' of results (they are not really 'rows' in JSON format so perhaps I should say many thousands of result items) seems perfectly performant.

Would you mind trying those changes - one or more of them as you think appropriate - and let us know how you get on?

David

**Comment by FDever17** [comment]
Hi David,

Thank you for responding so soon. 

I have given that a go and it seems to have worked. I changed those endpoint settings as outlined and the tool is now returning more groups that I'd expect to see, so thank you very much.

We do have something in the region of 1500+ custom groups so I may need to increase the limit such that all of the groups are returned, however not every one is populated so I don't expect them all to be returned. I will have a look at the final output and see.

I did get a message at the end that reads:

"errorcode":10530 "message":"The identity \"members\" was not found etc..

if that's of any interest.

Thanks,
Fraser

**Comment by dwstern** [comment]
Thank you for being the guinea pig and testing that, Fraser - I'll update the code to include those limit-increasing parameters as soon I can (probably not today as I'm in calls all day). Did you get a line number for that error message? Probably a typo in something I asked you to try, but I'll test here and make sure it's okay before I push it to the master branch! Many thanks for raising this - good spot.

**Comment by FDever17** [comment]
Not a problem at all David, happy to help. Perfect, they have definitely helped to get more groups.

The error doesn't appear to have a line number at all. I am piping the output to a text file for the moment and the error is at the very end after listing the groups. I have copied the full message below:

{"errorCode":10530,"message":"The identity \"members\" was not found.","details":["traceId: d751f54acde538ff","path: /identities/groups//members"],"links":[],"version":2,"httpStatusCode":404}

This could be something to do with our groups specifically, I may need to increase the endpoint value so that it includes more information.

**Comment by FDever17** [comment]
Hi David - Quick update, I increased the numbers to limit=100000 for each option and I encountered the same message at the same point in the file.

**Comment by dwstern** [comment]
Great - thanks for that Fraser. Okay, so it's probably not due to the limit being hit, it'll be something else. I'll see if I can replicate that issue here :)

**Comment by FDever17** [comment]
No problem at all, let me know if you find anything. Thank you again!

**Comment by dwstern** [comment]
Reopening at Vanessa Anness's request. Please provide more information to help us understand what is and is not being retrieved by this tool, so that we can try to figure out what seems to be missing and why.

**Comment by FDever17** [comment]
Hi David, I have experimented with a few option changes and it appears that we are still getting that search error when trying to list out all of the groups. As is appears to list the groups in a seemingly random order, I am unable to narrow down where the issue is. The change in the limit has provided us with more groups (thank you again) but not all.

I believe it could be something to do with the URI of the group as we were also having an issue with the explain access.py tool as it appeared to be pulling through multiple uris or the formatting was wrong for the result (in list effective permissions). We removed the folder and the effectiveaccess permissions script now works. 

I mention this as possibly there is some correlation between the two, in that the way that the groups are being listed in the api call is not being translated properly for all groups, or possibly duplicate groups. I can't seem to find any other information, but I am running the tool on debug at the moment to see if any other information comes through.

Fraser

**Comment by FDever17** [comment]
Update - No other information is provided from the debug other than: 

{"errorCode":10530,"message":"The identity "members" was not found.","details":["traceId: 3172d47ffd7db328","path: /identities/groups//members"],"links":[],"version":2,"httpStatusCode":404}

**Comment by dwstern** [comment]
Hi Fraser,

On Friday I updated the code for listgroupsandmembers.py with a fix that differed slightly from the code I asked you to try. My colleague Gerry then reviewed the changes and merged them into the master branch so that they are live. Have you used the latest version at all?

> @dwstern dwstern mentioned this issue 5 days ago
> Increase limits on rows returned to 10000 in listgroupsandmembers.py #55
>  Merged
> @gerrynelson63 gerrynelson63 closed this in #55 5 days ago

On line 108 of listgroupsandmembers.py: I asked you to change endpoint='/identities/users/'+memberid to endpoint='/identities/users/'+memberid + '/limit=10000'. That was a typo (sorry) - I separated the limit=1000 from the rest with a '/' when it should have been a '?'. The correct change should have been to make it say:
endpoint='/identities/users/'+memberid+'?limit=10000'

That line of the code only comes into play when you use the -e argument to ask it to output email addresses (or otherwise make show_email=true), so I assume you're doing that?

The groups are output by this script in the order they come from the API, which as you say is semi-random. You'd need to sort them yourself if you need to. 

If the code change above (or using the latest version from here) doesn't get all the groups, I'd need to start a debugging process. Here's how I'd do it - since it's probably faster for you to try this than for us to do it remotely in an exchange of comments here :)

I'd start with checking whether all the groups are returned - both because that's the first API call in the code (and the others are based on its results) and because that's the step which you say is not returning all the results. If it were me, I would first put a sys.exit() statement immediately line 74, or else comment out everything after line 74, and run the modified script in debug mode with your usual arguments. In its debug output, can you find the groupslist_result_json string? Can you copy it into a text editor that does JSON formatting? I like Notepad++ with the JSTool plugin for this, but other text editors and plugins will also do a good job. How many groups does that say are returned - there should be a count attribute near the very top or the very bottom? Do you see anything which indicates that it is a different number than the actual number of results in the JSON results string? How does this number compare with the number of groups you expect? Do you see anything odd about the groups (you mention their URIs) that might be a clue and can you share an example, e.g. of a URI that seems odd to you?

But before all that, do please check you're using the latest version of the code, either from here or by correcting my typo in my earlier message for what the endpoint string should be in line 108.

If this gets too complex, I'm happy to set up a phone call to help!

Kind regards,

David

**Comment by FDever17** [comment]
Hi David,

Apologies for the delay it has been a busy week! I made the amendment to the script and re-ran. It came back with the same error. I have also run the sys.exit() command with the debug, I have now been able to identify where the error is occurring but I am unsure as to why. I think if we set up a call that would be great, as you say much easier than here.
Many Thanks,
Fraser

**Comment by dwstern** [comment]
Hi Fraser, further to our call earlier, I've made a branch with the same fix to listgroupsandmembers.py here in GitHub that we tried out on your environment. It works fine in my test environment. Hopefully that really does resolve this issue.
